
-- Syntax for executing a stored procedure on a linked server using EXECUTE AT
exec('BEGIN UACC_ONCORE_RW_UTILS.UPDATE_PROTOCOLS; END;') at ONCOREPROD;
exec('BEGIN UACC_ONCORE_RW_UTILS.UPDATE_PROTOCOLS_UNIQUE_INFO; END;') at ONCOREPROD;
exec('BEGIN UACC_ONCORE_RW_UTILS.UPDATE_PROTOCOL_SUBJECTS_INFO; END;') at ONCOREPROD;
exec('BEGIN UACC_ONCORE_RW_UTILS.CREATE_TB_ONCORE_DT4; END;') at ONCOREPROD;
